version: '3.4'

services:

  redis:
    image: redis:alpine
    volumes:
      - "redis_data:/data"
    networks: 
        - backend

  mosquitto:
    image: eclipse-mosquitto:2.0.11
    container_name: Mosquitto
    networks:
        - backend
    ports:
        - "1883:1883"

volumes:
    redis_data:

networks:
  backend:
    external: true
    name: connexity-backend
