version: '3.4'

services:

  redis:
    image: redis:alpine
    command: "redis-server --save 60 1"
    ports:
      - "6379:6379"
    
  mosquitto:
    image: eclipse-mosquitto:2.0.11
    container_name: Mosquitto
    networks:
        - backend
    ports:
        - "1883:1883"